In [3]:
import numpy as np

In [4]:
lista = [1, 2, 3]

In [5]:
np.array(lista)

array([1, 2, 3])

In [6]:
print(np.array(lista))

[1 2 3]


In [7]:
arreglo = np.array(lista)

In [8]:
arreglo.dtype

dtype('int64')

In [9]:
arreglo[0]

1

Ejercicio: Sumar 2 listas

In [10]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [12]:
arreglo

array([1, 2, 3])

In [11]:
arreglo + arreglo

array([2, 4, 6])

In [13]:
arreglo2 = [10, 20, 30, 40]

Ejercicio: Obtener una lista que contenga los números al cuadrado del 1 al 10

In [15]:
lista_vacia = []
for i in range(1,11):
    lista_vacia.append(i**2)
lista_vacia

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [16]:
[ x**2 for x in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [18]:
np.arange(1,11)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [24]:
np.array(arreglo2) + 150

array([160, 170, 180, 190])

In [26]:
lista = [1, 2, 3]
np.array(lista)

array([1, 2, 3])

In [25]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Calcular el IMC

In [27]:
peso = [ 80.4, 74.5, 99.5, 75.9, 105.5]

In [28]:
estatura = [1.80, 1.65, 1.72, 1.63, 1.80] 

In [29]:
imc = []

for i in range(len(peso)):
    imc.append(peso[i]/estatura[i]**2)

imc

[24.814814814814817,
 27.364554637281913,
 33.63304488912926,
 28.567127103014794,
 32.56172839506173]

In [30]:
imc = np.array(peso) / np.array(estatura)**2
imc

array([24.81481481, 27.36455464, 33.63304489, 28.5671271 , 32.5617284 ])

$$imc = \frac{peso}{estatura^2}$$

In [31]:
ejemplo = np.array([1 ,2 , 3 , "5"])
ejemplo

array(['1', '2', '3', '5'], dtype='<U21')

Condicionales

In [32]:
15 < 20

True

In [33]:
arreglo

array([1, 2, 3])

In [34]:
imc

array([24.81481481, 27.36455464, 33.63304489, 28.5671271 , 32.5617284 ])

In [35]:
imc > 30

array([False, False,  True, False,  True])

Filtro

In [36]:
imc[imc > 30]

array([33.63304489, 32.5617284 ])

In [37]:
list(imc[imc > 30])

[33.63304488912926, 32.56172839506173]

## Crear arrays

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [41]:
np.arange(15, 31)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
np.arange(10, 31, 5)

array([10, 15, 20, 25, 30])

Linspace

In [43]:
np.linspace(1, 2, 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [44]:
np.linspace(0,100, 4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [46]:
np.linspace(-5, 5 , 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [50]:
np.random.randint(10)

5

In [51]:
np.random.randint(50, 100)

76

In [52]:
np.random.randint(50, 100, 10)

array([56, 82, 53, 90, 87, 75, 93, 89, 72, 55])

In [54]:
# 0 - 1
np.random.rand(10)

array([0.49062418, 0.22665457, 0.69446769, 0.99093026, 0.44686664,
       0.16097311, 0.47029706, 0.38352658, 0.71077532, 0.0341098 ])

In [57]:
np.random.random()

array([0.15177434, 0.94470447, 0.07144404, 0.36801579, 0.18513258,
       0.88559498, 0.07630594, 0.03658721, 0.90321947, 0.35138874,
       0.48839594, 0.41996078, 0.39379938, 0.68596977, 0.11224037])

In [56]:
numeros_aleatorios = np.random.randint(10, 20, 10)
numeros_aleatorios.sort()
numeros_aleatorios

array([10, 10, 12, 14, 15, 15, 16, 16, 18, 19])

In [ ]:
.mean()

## Matrices 

In [58]:
sublista = [ [1.80, 83.4 ], [1.76, 80.5], [1.78, 82.5] ]

In [63]:
matriz = np.array(sublista)
matriz

array([[ 1.8 , 83.4 ],
       [ 1.76, 80.5 ],
       [ 1.78, 82.5 ]])

In [64]:
matriz[:, 0]

array([1.8 , 1.76, 1.78])

In [65]:
matriz.shape

(3, 2)

In [66]:
matriz[0, :]

array([ 1.8, 83.4])

In [67]:
matriz[1:, :]

array([[ 1.76, 80.5 ],
       [ 1.78, 82.5 ]])

In [68]:
matriz[[0,2], :]

array([[ 1.8 , 83.4 ],
       [ 1.78, 82.5 ]])

In [70]:
matriz

array([[ 1.8 , 83.4 ],
       [ 1.76, 80.5 ],
       [ 1.78, 82.5 ]])

In [69]:
np.where(matriz > 1.79)

(array([0, 0, 1, 2]), array([0, 1, 1, 1]))

In [71]:
filas , columnas = np.where(matriz > 1.79)

In [72]:
filas

array([0, 0, 1, 2])

In [73]:
columnas

array([0, 1, 1, 1])

In [75]:
for fila, columna in zip(filas, columnas):
    print(f'{fila} {columna} {matriz[fila][columna]}')

0 0 1.8
0 1 83.4
1 1 80.5
2 1 82.5
