In [3]:
import numpy as np

In [4]:
lista = [1, 2, 3]

In [5]:
np.array(lista)

array([1, 2, 3])

In [6]:
print(np.array(lista))

[1 2 3]


In [7]:
arreglo = np.array(lista)

In [8]:
arreglo.dtype

dtype('int64')

In [9]:
arreglo[0]

1

Ejercicio: Sumar 2 listas

In [10]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [12]:
arreglo

array([1, 2, 3])

In [11]:
arreglo + arreglo

array([2, 4, 6])

In [13]:
arreglo2 = [10, 20, 30, 40]

Ejercicio: Obtener una lista que contenga los números al cuadrado del 1 al 10

In [15]:
lista_vacia = []
for i in range(1,11):
    lista_vacia.append(i**2)
lista_vacia

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [16]:
[ x**2 for x in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [18]:
np.arange(1,11)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [24]:
np.array(arreglo2) + 150

array([160, 170, 180, 190])

In [26]:
lista = [1, 2, 3]
np.array(lista)

array([1, 2, 3])

In [25]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Calcular el IMC

In [27]:
peso = [ 80.4, 74.5, 99.5, 75.9, 105.5]

In [28]:
estatura = [1.80, 1.65, 1.72, 1.63, 1.80] 

In [29]:
imc = []

for i in range(len(peso)):
    imc.append(peso[i]/estatura[i]**2)

imc

[24.814814814814817,
 27.364554637281913,
 33.63304488912926,
 28.567127103014794,
 32.56172839506173]

In [30]:
imc = np.array(peso) / np.array(estatura)**2
imc

array([24.81481481, 27.36455464, 33.63304489, 28.5671271 , 32.5617284 ])

$$imc = \frac{peso}{estatura^2}$$

Condicionales